version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: oj
    versions:
    - 3.11.4
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: bootsnap
    versions:
    - 1.7.1
    - 1.7.3
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: timecop
    versions:
    - 0.9.3
    - 0.9.4
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
  - dependency-name: faker
    versions:
    - 2.16.0
  - dependency-name: puma
    versions:
    - 5.2.1
