PreCommit:
  ALL:
    problem_on_unmodified_line: ignore
  RuboCop:
    enabled: true
  TrailingWhitespace:
    enabled: true
    exclude:
      - '/db/**/*'

CommitMsg:
  CapitalizedSubject:
    enabled: false
