version: "3.1"
services:
  web:
    build: "."
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 9091:3000
    volumes:
      - .:/web
    environment:
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - CORS_ORIGINS=http://localhost:9090
      - DATABASE_URL=postgresql://db_user:db_pass@db:5432/budget_development
      - RAILS_ENV=development
  db:
    image: postgres:11.14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_USER=db_user
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
