default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_development

test:
  <<: *default
  database: budget_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "budget_production") %>
