default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_development

test:
  <<: *default
  database: budget_test

production:
  <<: *default
  database: <%= ENV['INAB_BACK_DATABASE_NAME'] %>
  username: <%= ENV['INAB_BACK_DATABASE_USERNAME'] %> 
  password: <%= ENV['INAB_BACK_DATABASE_PASSWORD'] %>
