default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['BUDGET_DB_USERNAME'] %>
  password: <%= ENV['BUDGET_DB_PASSWORD'] %>

development:
  <<: *default
  database: budget_development

test:
  <<: *default
  database: budget_test

production:
  <<: *default
  database: <%= ENV['BUDGET_DB_NAME'] %>
