name: budget-pipe

on: push

jobs:
  specs:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Cache bundle
        uses: ruby/setup-ruby@v1.80.0
        with:
          bundler-cache: true
      - name: Creating DB
        run: bundle exec rake db:create db:schema:load
      - name: Running specs
        run: bundle exec rspec --format progress
    env:
      RAILS_ENV: test
      PGHOST: localhost
      BUDGET_DB_USERNAME: test
      BUDGET_DB_PASSWORD: test
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache bundle
        uses: ruby/setup-ruby@v1.80.0
        with:
          bundler-cache: true
      - name: Running rubocop
        run: bundle exec rubocop
